<!-- Required meta tags -->
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
<meta name="author" content="Marko Grujic"/>
<meta name="description" content="Stranica za započinjanje i odjavu predavanja."/>
<meta name="keywords" content=""/>
<link rel="shortcut icon" href="img/favicon.ico"/>
<!-- Bootstrap CSS -->
<link href="css/bootstrap.css" rel="stylesheet" type="text/css"/>
<!-- Font Awesome-->
<link href="css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<!--theme css-->
<link href="css/style-login.css" rel="stylesheet" type="text/css"/>
<link href="css/style.css" rel="stylesheet" type="text/css"/>
<link href="css/responsive.css" rel="stylesheet" type="text/css"/>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="js/jquery.js" type="text/javascript"></script>
<script src="js/popper.js" type="text/javascript"></script>
<script src="js/bootstrap.min.js" type="text/javascript"></script>
<!--datepicker-->
<link href="css/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="js/jquery-1.12.4.js" type="text/javascript"></script>
<script src="js/jquery-ui.js" type="text/javascript"></script>
<!--disabledRightClickAndCtrl-->
<script src="js/disabledRightClickAndCtrl.js" type="text/javascript"></script>
<!--SWEAT ALERT-->
<script src="js/sweetalert.js" type="text/javascript"></script>
<script src="js/bio.js" type="text/javascript"></script>
<script src="js/Main.js" type="text/javascript"></script>

